nodeorder.settings:
  type: config_object
  label: Settings
  mapping:
    override_taxonomy_page:
      type: boolean
    show_links_on_node:
      type: boolean
    link_to_ordering_page:
      type: boolean
    link_to_ordering_page_taxonomy_admin:
      type: boolean
    vocabularies:
      type: sequence
      sequence:
        - type: boolean
          label: "Vocabulary"
